### ISSUE TITLE
Update to or add support for jsPsych v8

### ISSUE THREAD

**Issue by becky-gilbert** [lookit/lookit-jspsych#34]
## Summary

[jsPsych v8](https://github.com/jspsych/jsPsych/discussions/3346) was just released. We should decide if we want to stick with just supporting jsPsych v7 for now, or update to v8, or allow researchers to choose a version in their study config.

## Description

Sticking with v7 would mean that we don't need to make changes, and current jsPsych users would not need to update their code to run their jsPsych study on CHS. However there are some maintainability issues to think about. For instance, our survey-consent plugin uses the jsPsych survey plugin, and I can no longer update that plugin for jsPsych v7 (without creating/maintaining a separate v7 fork, which is not ideal). And more generally, we will start missing out on all future bug fixes and features that will only be added in v8.

**Comment by mekline** [comment]
If I'm a researcher with a v7 study, how much work does it probably take me to update to v8 in practice?

**Comment by becky-gilbert** [comment]
Good question. Very little work, I think. Most of the changes were internal and only relevant to developers. There are some researcher-facing changes, but they only affect a subset of users (those using certain functions/parameters) and should be easy to update if necessary.

**Comment by becky-gilbert** [comment]
Closing this as completed in #41. 

We ended up upgrading to jsPsych v8 to fix a bug. We can decide whether to also support v7, but we probably won't need to do that as most of the v8 changes were internal/developer-facing. A researcher with v7 study code should be able to run their study using jsPsych v8 with little or no changes.
