### ISSUE TITLE
Support different consent templates

### ISSUE THREAD

**Issue by becky-gilbert** [lookit/lookit-jspsych#62]
## Summary

Our `consentVideo` plugin currently just runs the consent template 005. But EFP has a few different consent templates that users can choose from (with variations in the available parameters). And we may need to add more templates in the future. Here are the templates available in EFP's [video-consent frame](https://lookit.readthedocs.io/projects/frameplayer/en/latest/components/exp-lookit-video-consent/doc.html):

* consent_001
* consent_002
* consent_003
* consent_004
* consent_005
* consent_garden

@mekline do you want to support all of these templates in jsPsych studies?

To do:
- [x] Add a template parameter to the video consent plugin: defaults to 005 and allows one of the pre-defined template name strings as the value (and throw error for template not found)
- [x] ~~Implement the changes to the handlebars template that are conditional on the consent template parameter~~
- [x] Add a templates package that takes the template choice and parameters and returns the HTML
- [ ] Update the [video consent documentation](https://github.com/lookit/lookit-jspsych/blob/main/packages/record/README.md#video-consent) to explain the template options and any parameters that are conditional on templates. #100

**Comment by mekline** [comment]
Just consent_005 and garden for now!
